import express from "express";
import fs from "fs/promises";
import path from "path";
import puppeteer from "puppeteer";
import { fileURLToPath } from "url";
import cloudinary from "../config/cloudinary.js";
import Commission from "../models/Commission.js";
import CommissionRule from "../models/CommissionRule.js";
import Customer from "../models/Customer.js";
import DeliveryMan from "../models/DeliveryMan.js";
import Product from "../models/Product.js";
import PurchaseOrder from "../models/PurchaseOrder.js";
import SalesMan from "../models/SalesMan.js";
import SalesOrder from "../models/SalesOrder.js";
import SalesOwner from "../models/SalesOwner.js";
import DebitNote from "../models/DebitNote.js";
import CreditNote from "../models/CreditNote.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const router = express.Router();

// Helper function to generate placeholder invoice image using canvas library
async function generatePlaceholderInvoice(sale, type = "order") {
  try {
    console.log(`📄 Generating placeholder ${type} invoice...`);
    
    // Create a simple SVG-based placeholder
    const invoiceTitle = type === "tax" ? "TAX INVOICE" : "ORDER DETAILS";
    const svg = `
      <svg width="800" height="1200" xmlns="http://www.w3.org/2000/svg">
        <rect width="800" height="1200" fill="white" stroke="black" stroke-width="2"/>
        
        <!-- Header -->
        <rect width="800" height="100" fill="#1a5490"/>
        <text x="400" y="50" font-size="32" font-weight="bold" fill="white" text-anchor="middle">PEARL AGENCY</text>
        <text x="400" y="80" font-size="14" fill="#ccc" text-anchor="middle">Invoice Management System</text>
        
        <!-- Title -->
        <text x="400" y="150" font-size="24" font-weight="bold" fill="#000" text-anchor="middle">${invoiceTitle}</text>
        
        <!-- Invoice Details -->
        <text x="50" y="200" font-size="12" font-weight="bold" fill="#000">Invoice ID:</text>
        <text x="200" y="200" font-size="12" fill="#000">${sale.invoiceId}</text>
        
        <text x="50" y="230" font-size="12" font-weight="bold" fill="#000">Customer:</text>
        <text x="200" y="230" font-size="12" fill="#000">${sale.customer?.name || "N/A"}</text>
        
        <text x="50" y="260" font-size="12" font-weight="bold" fill="#000">Warehouse:</text>
        <text x="200" y="260" font-size="12" fill="#000">${sale.warehouse || "N/A"}</text>
        
        <text x="50" y="290" font-size="12" font-weight="bold" fill="#000">Date:</text>
        <text x="200" y="290" font-size="12" fill="#000">${new Date(sale.orderDate || sale.createdAt || new Date()).toLocaleDateString()}</text>
        
        <!-- Items Header -->
        <rect x="50" y="330" width="700" height="30" fill="#e8e8e8" stroke="black" stroke-width="1"/>
        <text x="60" y="355" font-size="11" font-weight="bold">Product Name</text>
        <text x="450" y="355" font-size="11" font-weight="bold">Qty</text>
        <text x="520" y="355" font-size="11" font-weight="bold">Price</text>
        <text x="640" y="355" font-size="11" font-weight="bold">Total</text>
        
        <!-- Items -->
        ${(sale.items || []).slice(0, 8).map((item, idx) => {
          const y = 380 + (idx * 35);
          return `
            <rect x="50" y="${y}" width="700" height="30" stroke="#ddd" stroke-width="1"/>
            <text x="60" y="${y + 20}" font-size="10">${item.name || "Item"}</text>
            <text x="450" y="${y + 20}" font-size="10">${item.qty || 0}</text>
            <text x="520" y="${y + 20}" font-size="10">₹${item.sellingPrice || 0}</text>
            <text x="640" y="${y + 20}" font-size="10">₹${(item.qty * item.sellingPrice).toFixed(2)}</text>
          `;
        }).join("")}
        
        <!-- Totals Section -->
        <rect x="50" y="700" width="700" height="100" fill="#f5f5f5" stroke="black" stroke-width="1"/>
        <text x="450" y="730" font-size="11" font-weight="bold">Subtotal:</text>
        <text x="640" y="730" font-size="11">₹${sale.subtotal || 0}</text>
        
        <text x="450" y="760" font-size="11" font-weight="bold">Tax:</text>
        <text x="640" y="760" font-size="11">₹${sale.totalTax || 0}</text>
        
        <text x="450" y="790" font-size="12" font-weight="bold" fill="#d32f2f">Grand Total:</text>
        <text x="640" y="790" font-size="12" font-weight="bold" fill="#d32f2f">₹${sale.grandTotal || 0}</text>
        
        <!-- Footer -->
        <text x="400" y="1100" font-size="10" fill="#666" text-anchor="middle">Generated by Pearl ERP System</text>
        <text x="400" y="1120" font-size="9" fill="#999" text-anchor="middle">For official use only</text>
      </svg>
    `;
    
    // Convert SVG to base64
    const base64Svg = Buffer.from(svg).toString('base64');
    
    // Upload to Cloudinary
    const upload = await cloudinary.uploader.upload(
      `data:image/svg+xml;base64,${base64Svg}`,
      {
        folder: "pearls-erp/invoices",
        public_id: `PLACEHOLDER_${type.toUpperCase()}_${sale.invoiceId}_${Date.now()}`,
      }
    );
    
    console.log(`✅ Placeholder ${type} invoice created:`, upload.secure_url);
    return upload.secure_url;
  } catch (err) {
    console.error(`❌ Error creating placeholder invoice:`, err);
    // Return a simple text-based response
    return `data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjEyMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHJlY3Qgd2lkdGg9IjgwMCIgaGVpZ2h0PSIxMjAwIiBmaWxsPSJ3aGl0ZSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSIyIi8+PHRleHQgeD0iNDAwIiB5PSI2MDAiIGZvbnQtc2l6ZT0iMjQiIGZpbGw9IiMzMzMiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkludm9pY2U6ICR7c2FsZS5pbnZvaWNlSWR9PC90ZXh0Pjwvc3ZnPg==`;
  }
}

// Helper function to launch browser with proper Chrome detection
async function launchBrowser() {
  try {
    console.log("🔍 Attempting to launch Puppeteer browser...");
    
    // Try default launch first (uses bundled Chrome)
    const browser = await puppeteer.launch({
      headless: true,
      args: [
        '--font-render-hinting=none',
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage'
      ],
    });
    
    console.log("✅ Browser launched successfully with bundled Chrome");
    return browser;
  } catch (err) {
    console.error("❌ Browser launch failed:", err.message);
    console.log("📄 Falling back to placeholder invoice generation...");
    return null; // Return null to signal fallback
  }
}

// Cache for logo - using WeakMap to avoid naming conflicts
const logoCache = { data: null };

// Helper function to get logo as base64 data URI
async function getLogoDataUri() {
  if (logoCache.data) return logoCache.data; // Cache the logo
  try {
    const logoPath = path.join(__dirname, "../../public/logo.jpeg");
    const logoBuffer = await fs.readFile(logoPath);
    logoCache.data = `data:image/jpeg;base64,${logoBuffer.toString('base64')}`;
    console.log("✅ Logo loaded successfully");
    return logoCache.data;
  } catch (err) {
    console.warn("⚠️ Logo not found:", err.message);
    return null;
  }
}

// Helper function to ensure items have pricing information
async function enrichItemsWithPrices(items, isPurchase = false) {
  if (!Array.isArray(items)) return [];

  return await Promise.all(items.map(async (item) => {
    // If price is already set and non-zero, use it
    if (isPurchase && item.purchasePrice && item.purchasePrice > 0) {
      return item;
    }
    if (!isPurchase && item.sellingPrice && item.sellingPrice > 0) {
      return item;
    }

    // If price is missing, try to fetch from Product model
    if (item.productId) {
      try {
        const product = await Product.findById(item.productId).lean();
        if (product) {
          if (isPurchase && !item.purchasePrice) {
            item.purchasePrice = product.purchasePrice || 0;
          } else if (!isPurchase && !item.sellingPrice) {
            item.sellingPrice = product.sellingPrice || 0;
          }
        }
      } catch (err) {
        console.log(`Could not fetch product prices for ${item.productId}`);
      }
    }

    return item;
  }));
}

router.get("/", async (req, res) => {
  try {
    const purchases = await PurchaseOrder.find().lean();
    const sales = await SalesOrder.find().lean();
    const debitNotes = await DebitNote.find({ status: "Created" }).lean();
    const creditNotes = await CreditNote.find({ status: "Created" }).lean();

    const purchaseMapped = await Promise.all(purchases.map(async (p) => ({
      _id: p._id,
      type: "PURCHASE",
      date: p.date || p.createdAt,
      invoiceId: p.invoiceId,
      party: p.vendor,
      warehouse: p.warehouse,
      items: await enrichItemsWithPrices(p.items, true),
      subtotal: p.subtotal,
      totalTax: p.totalTax,
      transportCharge: p.transportCharge || 0,
      grandTotal: p.grandTotal,
    })));

    const debitNoteMapped = await Promise.all(debitNotes.map(async (dn) => ({
      _id: dn._id,
      type: "PURCHASE RETURN",
      date: dn.createdAt,
      invoiceId: dn.debitNoteId,
      party: dn.vendor?.name || "Unknown",
      items: dn.items || [],
      subtotal: dn.subtotal,
      totalTax: dn.totalTax,
      grandTotal: -dn.grandTotal, // Negative because it reduces purchase liability
      originalInvoiceId: dn.originalInvoiceId,
      reason: dn.reason,
    })));

    const salesReturnMapped = await Promise.all(creditNotes.map(async (cn) => ({
      _id: cn._id,
      type: "SALES RETURN",
      date: cn.createdAt,
      invoiceId: cn.creditNoteId,
      party: cn.customer?.name || "Unknown",
      items: cn.items || [],
      subtotal: cn.subtotal,
      totalTax: cn.totalTax,
      grandTotal: -cn.grandTotal, // Negative because it reduces sales receivable
      originalInvoiceId: cn.originalInvoiceId,
      reason: cn.reasonForReturn,
    })));

    const salesMapped = [];

    for (const s of sales) {
      const salesOrderRow = {
        _id: s._id,
        type: "SALES ORDER",
        recordId: `${s._id}-SO`,
        date: s.createdAt,
        invoiceId: s.invoiceId,
        party: s.customer?.name || "",
        warehouse: s.warehouse,
        openingBalance: s.openingBalance,
        closingBalance: s.openingBalance, // Sales order doesn't affect balance
        items: await enrichItemsWithPrices(s.items, false),
        sampleItems: await enrichItemsWithPrices(s.sampleItems, false),
        subtotal: s.subtotal,
        totalTax: s.totalTax,
        transportCharge: s.transportCharge,
        grandTotal: s.grandTotal,
        invoiceGenerated: s.invoiceGenerated || false,
      };
      salesMapped.push(salesOrderRow);

      // If invoice was generated, create a separate SALES INVOICE row with invoice items
      if (s.invoiceGenerated) {
        // Calculate closing balance based on invoice amount only
        const invoiceAmount = s.invoiceGrandTotal || s.grandTotal;
        const invoiceOpeningBalance = s.openingBalance || 0;
        const invoiceClosingBalance = invoiceOpeningBalance + invoiceAmount;

        const salesInvoiceRow = {
          _id: s._id,
          type: "SALES INVOICE",
          recordId: `${s._id}-SI`,
          date: s.invoiceDate || s.createdAt,
          invoiceId: s.invoiceId,
          party: s.customer?.name || "",
          warehouse: s.warehouse,
          openingBalance: invoiceOpeningBalance,
          closingBalance: invoiceClosingBalance,
          // Use invoice items if they exist, otherwise fall back to original items
          items: await enrichItemsWithPrices(s.invoiceItems || s.items, false),
          sampleItems: await enrichItemsWithPrices(s.invoiceSampleItems || s.sampleItems, false),
          subtotal: s.invoiceSubtotal || s.subtotal,
          totalTax: s.invoiceTotalTax || s.totalTax,
          transportCharge: s.invoiceTransportCharge || s.transportCharge,
          grandTotal: invoiceAmount,
          invoiceGenerated: true,
        };
        salesMapped.push(salesInvoiceRow);
      }
    }

    const merged = [...purchaseMapped, ...debitNoteMapped, ...salesMapped, ...salesReturnMapped].sort(
      (a, b) => new Date(b.date) - new Date(a.date)
    );

    res.json(merged);
  } catch (err) {
    console.error("Pearls Book GET error:", err);
    res.status(500).json({ message: "Failed to load Pearls Book" });
  }
});

async function checkStockAvailability(saleItems, warehouse) {
  for (const saleItem of saleItems) {
    console.log(`\n📦 Checking stock for: ${saleItem.name} (ProductId: ${saleItem.productId})`);

    // Check Product model's totalQty (source of truth)
    const product = await Product.findById(saleItem.productId);

    if (!product) {
      throw new Error(`Product not found: ${saleItem.name}`);
    }

    const totalAvailable = product.totalQty || 0;
    console.log(`  📍 Warehouse: ${warehouse}`);
    console.log(`  Product totalQty: ${totalAvailable}, Required: ${saleItem.qty}`);

    if (totalAvailable < saleItem.qty) {
      throw new Error(
        `Insufficient stock for ${saleItem.name}. Available: ${totalAvailable}`
      );
    }
  }
}


async function reduceStockFIFO(saleItems, warehouse) {
  const lowStockAlerts = [];

  for (const saleItem of saleItems) {
    // Reduce from Product totalQty
    const product = await Product.findById(saleItem.productId);

    if (!product) {
      throw new Error(`Product not found: ${saleItem.name}`);
    }

    // Reduce totalQty
    const newTotalQty = product.totalQty - saleItem.qty;
    await Product.findByIdAndUpdate(saleItem.productId, {
      totalQty: newTotalQty
    });

    console.log(`✅ Stock reduced for ${saleItem.name}: ${product.totalQty} → ${newTotalQty}`);

    // Check for low stock alert
    if (newTotalQty < 10) {
      lowStockAlerts.push({
        product: saleItem.name,
        warehouse: warehouse,
        remainingQty: newTotalQty,
      });
    }
  }

  return lowStockAlerts;
}

function getFormattedDateTime() {
  const now = new Date();
  return now.toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

// Generate HTML Invoice - PAGE 1: ORDER DETAILS + SAMPLE ITEMS (MATCHING FIRST IMAGE)
async function generateInvoiceOrderPage(sale, copyTitle = "ORIGINAL INVOICE", isReEdited = false) {
  const logoDataUri = await getLogoDataUri();
  
  const itemsHTML = sale.items.map((item) => `
    <tr>
      <td style="padding: 10px; border: 1px solid #999; font-size: 11px; color: #000;">${item.name}</td>
      <td style="padding: 10px; border: 1px solid #999; text-align: center; font-size: 11px; color: #000;">${item.hsn}</td>
      <td style="padding: 10px; border: 1px solid #999; text-align: center; font-size: 11px; color: #000;">${item.gst}%</td>
      <td style="padding: 10px; border: 1px solid #999; text-align: center; font-size: 11px; color: #000;">${item.qty}</td>
      <td style="padding: 10px; border: 1px solid #999; text-align: right; font-size: 11px; color: #000;">₹${item.sellingPrice.toFixed(2)}</td>
      <td style="padding: 10px; border: 1px solid #999; text-align: center; font-size: 11px; color: #000;">Kg</td>
      <td style="padding: 10px; border: 1px solid #999; text-align: right; font-size: 11px; color: #000;">₹${(item.total || 0).toFixed(2)}</td>
    </tr>
  `).join('');

  const sampleItemsHTML = sale.sampleItems && sale.sampleItems.length > 0 ? `
    <div style="margin-top: 15px; page-break-inside: avoid;">
      <div style="background-color: #1a365d; color: white; padding: 8px; margin: 0; font-size: 11px; font-weight: bold;">SAMPLE PRODUCTS (NOT BILLED)</div>
      <table style="width: 100%; border-collapse: collapse; margin: 0;">
        <tr style="background-color: #f0f0f0;">
          <th style="padding: 8px; border: 1px solid #999; text-align: left; font-size: 9px; font-weight: bold;">Description of Goods</th>
          <th style="padding: 8px; border: 1px solid #999; text-align: center; font-size: 9px; font-weight: bold;">HSN</th>
          <th style="padding: 8px; border: 1px solid #999; text-align: center; font-size: 9px; font-weight: bold;">Qty</th>
          <th style="padding: 8px; border: 1px solid #999; text-align: right; font-size: 9px; font-weight: bold;">Rate</th>
          <th style="padding: 8px; border: 1px solid #999; text-align: right; font-size: 9px; font-weight: bold;">Total</th>
        </tr>
        ${sale.sampleItems.map((item) => `
          <tr>
            <td style="padding: 8px; border: 1px solid #999; font-size: 9px; color: #000;">${item.name}</td>
            <td style="padding: 8px; border: 1px solid #999; text-align: center; font-size: 9px; color: #000;">${item.hsn}</td>
            <td style="padding: 8px; border: 1px solid #999; text-align: center; font-size: 9px; color: #000;">${item.qty}</td>
            <td style="padding: 8px; border: 1px solid #999; text-align: right; font-size: 9px; color: #000;">₹${item.sellingPrice.toFixed(2)}</td>
            <td style="padding: 8px; border: 1px solid #999; text-align: right; font-size: 9px; color: #000;">₹${(item.qty * item.sellingPrice).toFixed(2)}</td>
          </tr>
        `).join('')}
      </table>
    </div>
  ` : '';

    const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Invoice - Order Details</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; background: white; padding: 30px; color: #333; }
        .invoice-container { max-width: 800px; margin: 0 auto; border: 3px solid #1e40af; padding: 30px; position: relative; }
        .header-top { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; border-bottom: 2px solid #1e40af; padding-bottom: 20px; }
        .logo-section { display: flex; gap: 20px; align-items: center; }
        .logo-section img { width: 100px; height: 100px; object-fit: contain; }
        .company-info-box { text-align: right; }
        .company-info-box p { font-size: 13px; margin-bottom: 4px; font-weight: 500; }
        .sender-buyer { display: flex; gap: 30px; margin-bottom: 30px; }
        .sender-buyer-item { flex: 1; padding: 15px; border: 1px solid #e5e7eb; border-radius: 6px; background: #f8fafc; }
        .sender-buyer-item h3 { font-size: 13px; color: #1e40af; margin-bottom: 10px; border-bottom: 1px solid #cbd5e1; padding-bottom: 6px; text-transform: uppercase; }
        .sender-buyer-item p { font-size: 12px; line-height: 1.5; }
        .order-details-box { background: #1e40af; color: white; padding: 8px 15px; font-size: 14px; font-weight: bold; margin-bottom: 15px; border-radius: 4px; }
        .order-details { display: flex; justify-content: space-between; margin-bottom: 15px; border-bottom: 1px dashed #cbd5e1; padding-bottom: 8px; }
        .order-details div { font-size: 15px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px; }
        th { background: #1e40af; color: white; padding: 12px; text-align: left; font-weight: 600; border: 1px solid #1e3a8a; }
        td { padding: 10px 12px; border: 1px solid #e5e7eb; }
        .summary-section { display: flex; justify-content: space-between; margin-top: 25px; gap: 30px; }
        .summary-box { flex: 1; border: 1px solid #e5e7eb; border-radius: 6px; padding: 15px; background: #f8fafc; }
        .summary-row { display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 13px; }
        .summary-row.total { border-top: 2px solid #1e40af; padding-top: 10px; margin-top: 10px; font-weight: bold; color: #1e40af; font-size: 15px; }
        .balance-section { margin-top: 20px; border: 1px solid #cbd5e1; border-radius: 6px; padding: 15px; background: #fffbeb; }
        .balance-row { display: flex; justify-content: space-between; font-size: 13px; margin-bottom: 6px; }
        .certification { font-size: 11px; font-style: italic; color: #666; margin-top: 35px; border-top: 1px solid #e5e7eb; padding-top: 15px; line-height: 1.5; }
        .copy-badge { text-align: right; font-weight: 800; color: #dc2626; font-size: 16px; margin-top: 20px; letter-spacing: 1px; text-transform: uppercase; }
        .footer-tag { text-align: center; color: #94a3b8; font-size: 10px; margin-top: 30px; }
      </style>
    </head>
    <body>
      <div class="invoice-container">
        <!-- HEADER -->
        <div class="header-top">
          <div class="logo-section">
            ${logoDataUri ? `<img src="${logoDataUri}" alt="Logo">` : ''}
            <div>
              <p style="font-size: 10px; font-weight: bold; color: #1e40af; margin-bottom: 4px;">Acknowledgement No:</p>
              <p style="font-size: 11px; font-weight: 900;">${sale.invoiceId}</p>
              <p style="margin-top: 5px; font-size: 9px;"><strong>Date: ${new Date(sale.createdAt || sale.orderDate || new Date()).toLocaleDateString("en-IN")}</strong></p>
            </div>
          </div>
          <div class="company-info-box">
            <p><strong>${sale.branchId?.name || "PEARL AGENCY"}</strong></p>
            <p>${sale.branchId?.address || "12/13, South By-Pass Road, Vanarpettai"}</p>
            <p>${sale.branchId?.city || "Tirunelveli"} - ${sale.branchId?.pincode || "627003"}, ${sale.branchId?.state || "Tamil Nadu"}</p>
            <p>Mobile: ${sale.branchId?.phone || "9429692970"} | GSTIN: ${sale.branchId?.gstin || "33DULPS2600Q1Z6"}</p>
            <p>GPAY No: ${sale.branchId?.gpayNo || ""}</p>
          </div>
        </div>

        <!-- SENDER & BUYER -->
        <div class="sender-buyer">
          <div class="sender-buyer-item">
            <h3>SENDER (FROM)</h3>
            <p><strong>${sale.branchId?.name || "PEARL AGENCY"}</strong></p>
            <p>${sale.branchId?.city || "Tirunelveli"} - ${sale.branchId?.pincode || "627003"}</p>
            <p>GSTIN: ${sale.branchId?.gstin || "33DULPS2600Q1Z6"}</p>
          </div>
          <div class="sender-buyer-item">
            <h3>BUYER (BILL TO)</h3>
            <p><strong>${sale.customer?.name || "Customer"}</strong></p>
            <p>${sale.customer?.address || "Address"}</p>
            <p>${sale.customer?.district || ""}, ${sale.customer?.state || ""}</p>
            <p>Mobile: ${sale.customer?.whatsapp || "-"}</p>
          </div>
        </div>

        <div class="order-details-box">${isReEdited ? "RE-EDIT " : ""}Order Details</div>
        <div class="order-details">
          <div><strong>Invoice No:</strong> ${sale.invoiceId}</div>
          <div><strong>Billing Person:</strong> ${sale.billingPersonName || "-"}</div>
        </div>

        <table>
          <thead>
            <tr>
              <th style="width: 35%;">Description</th>
              <th style="text-align: center;">HSN</th>
              <th style="text-align: center;">GST</th>
              <th style="text-align: center;">Qty</th>
              <th style="text-align: right;">Rate</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHTML}
          </tbody>
        </table>

        <div class="summary-section">
          <div class="summary-box">
             <div class="summary-row"><span>Subtotal:</span><span>₹${sale.subtotal?.toFixed(2) || '0.00'}</span></div>
             ${sale.totalTax?.igst > 0 ? 
               `<div class="summary-row"><span>IGST:</span><span>₹${(sale.totalTax?.igst || 0).toFixed(2)}</span></div>` : 
               `<div class="summary-row"><span>CGST:</span><span>₹${(sale.totalTax?.cgst || 0).toFixed(2)}</span></div>
                <div class="summary-row"><span>SGST:</span><span>₹${(sale.totalTax?.sgst || 0).toFixed(2)}</span></div>`
             }
             ${(sale.commonDiscount || sale.invoiceCommonDiscount) > 0 ? `<div class="summary-row"><span>Discount:</span><span style="color: #dc2626; font-weight: bold;">-₹${((sale.commonDiscount || sale.invoiceCommonDiscount) || 0).toFixed(2)}</span></div>` : ''}
             <div class="summary-row"><span>Transport:</span><span>₹${(sale.transportCharge || 0).toFixed(2)}</span></div>
             <div class="summary-row total"><span>GRAND TOTAL:</span><span>₹${sale.grandTotal?.toFixed(2) || '0.00'}</span></div>
          </div>
        </div>

        <div class="balance-section">
          <div class="balance-row"><span>Previous Balance:</span><strong>₹${(sale.openingBalance || 0).toFixed(2)}</strong></div>
          <div class="balance-row"><span>Closing Balance:</span><strong>₹${(sale.closingBalance || 0).toFixed(2)}</strong></div>
        </div>

        <div class="certification">Certified that the particulars given above are true and correct. E. & O.E.</div>
        <div class="copy-badge">${copyTitle}</div>
        <div class="footer-tag">Digitally generated by Pearls ERP System</div>
        
        ${sampleItemsHTML}
      </div>
    </body>
    </html>
    `;

  // Convert HTML to image using Puppeteer (A4 format: 800x1200px)
  const browser = await launchBrowser();
  
  // If browser failed to launch, use placeholder
  if (!browser) {
    console.log("📄 Using placeholder for order invoice (browser unavailable)");
    return await generatePlaceholderInvoice(sale, "order");
  }
  
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 880, height: 1200, deviceScaleFactor: 2 });
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const imageBuffer = await page.screenshot({ type: 'png', fullPage: true, scale: 2 });
    await browser.close();

    // Upload to Cloudinary
    const upload = await cloudinary.uploader.upload(
      `data:image/png;base64,${imageBuffer.toString("base64")}`,
      {
        folder: "pearls-erp/invoices",
        public_id: `INV_ORDER_${sale.invoiceId}_${Date.now()}`,
      }
    );

    return upload.secure_url;
  } catch (err) {
    console.error("❌ Error generating invoice page:", err);
    if (browser) await browser.close();
    // Fallback to placeholder if Puppeteer fails
    return await generatePlaceholderInvoice(sale, "order");
  }
}

// PAGE 2: TAX INVOICE (HSN BREAKDOWN)
async function generateInvoiceTaxPage(sale, copyTitle = "ORIGINAL INVOICE", backOrderSummary = [], invoiceNotes = "", isReEdited = false) {
  const logoDataUri = await getLogoDataUri();
  let totalCGST = 0, totalSGST = 0, totalIGST = 0;
  const hsnSummary = {};

  if (Array.isArray(sale.items)) {
    sale.items.forEach((item) => {
      if (!hsnSummary[item.hsn]) {
        hsnSummary[item.hsn] = {
          hsn: item.hsn,
          taxableValue: 0,
          cgstRate: item.cgst || 0,
          sgstRate: item.sgst || 0,
          igstRate: item.igst || 0,
          cgstAmount: 0,
          sgstAmount: 0,
          igstAmount: 0,
          total: 0,
        };
      }

      const baseAmount = item.sellingPrice * item.qty;
      const taxableValue = baseAmount - (item.discountAmount || 0);
      const cgstAmount = (taxableValue * item.cgst) / 100;
      const sgstAmount = (taxableValue * item.sgst) / 100;
      const igstAmount = (taxableValue * item.igst) / 100;

      hsnSummary[item.hsn].taxableValue += taxableValue;
      hsnSummary[item.hsn].cgstAmount += cgstAmount;
      hsnSummary[item.hsn].sgstAmount += sgstAmount;
      hsnSummary[item.hsn].igstAmount += igstAmount;
      hsnSummary[item.hsn].total += cgstAmount + sgstAmount + igstAmount + taxableValue;

      totalCGST += cgstAmount;
      totalSGST += sgstAmount;
      totalIGST += igstAmount;
    });
  }

  // 💡 Add transport GST to the common totals (as requested)
  const tCharge = sale.transportCharge || 0;
  const tGstPercent = sale.transportGstPercent || 18; // Default 18% if not specified
  const tGstAmount = (tCharge * tGstPercent) / 100;

  if (totalIGST > 0) {
    totalIGST += tGstAmount;
  } else {
    totalCGST += tGstAmount / 2;
    totalSGST += tGstAmount / 2;
  }

  const hsnArray = Object.values(hsnSummary);
  let totalTaxableValue = 0, grandTotal = 0;

  hsnArray.forEach((h) => {
    totalTaxableValue += h.taxableValue;
    grandTotal += h.total;
  });

  const rowsHTML = hsnArray.map((h) => `
    <tr>
      <td style="padding: 12px; border: 1px solid #ddd; font-size: 13px;">${h.hsn}</td>
      <td style="padding: 12px; border: 1px solid #ddd; text-align: right; font-size: 13px;">₹${h.taxableValue.toFixed(2)}</td>
      <td style="padding: 12px; border: 1px solid #ddd; font-size: 13px;">${h.cgstRate > 0 ? h.cgstRate + "% | ₹" + h.cgstAmount.toFixed(2) : "-"}</td>
      <td style="padding: 12px; border: 1px solid #ddd; font-size: 13px;">${h.sgstRate > 0 ? h.sgstRate + "% | ₹" + h.sgstAmount.toFixed(2) : "-"}</td>
      <td style="padding: 12px; border: 1px solid #ddd; text-align: right; font-size: 13px;">₹${h.total.toFixed(2)}</td>
    </tr>
  `).join('');

  const backOrderHTML = backOrderSummary && backOrderSummary.length > 0 ? `
    <div style="margin-top: 30px; border-top: 3px solid #dc2626; padding-top: 20px;">
      <h2 style="color: #dc2626; font-size: 18px; margin-bottom: 15px; text-transform: uppercase;">Back Order Summary</h2>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <thead>
          <tr style="background-color: #fee2e2;">
            <th style="padding: 12px; border: 1px solid #ddd; text-align: left; font-size: 13px;">Product Name</th>
            <th style="padding: 12px; border: 1px solid #ddd; text-align: center; font-size: 13px;">Ordered</th>
            <th style="padding: 12px; border: 1px solid #ddd; text-align: center; font-size: 13px;">Supplied</th>
            <th style="padding: 12px; border: 1px solid #ddd; text-align: center; font-size: 13px;">Back Order</th>
          </tr>
        </thead>
        <tbody>
          ${backOrderSummary.map(bo => `
            <tr>
              <td style="padding: 10px 12px; border: 1px solid #ddd; font-size: 13px;">${bo.product}</td>
              <td style="padding: 10px 12px; border: 1px solid #ddd; text-align: center; font-size: 13px;">${bo.requestedQty}</td>
              <td style="padding: 10px 12px; border: 1px solid #ddd; text-align: center; font-size: 13px;">${bo.confirmedQty}</td>
              <td style="padding: 10px 12px; border: 1px solid #ddd; text-align: center; font-size: 13px; font-weight: bold; color: #dc2626;">${bo.backOrderQty}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      ${invoiceNotes ? `<p style="font-size: 13px; font-style: italic; color: #4b5563;"><strong>Notes:</strong> ${invoiceNotes}</p>` : ''}
    </div>
  ` : '';

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Invoice - Tax Invoice</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; background: white; padding: 30px; }
        .invoice-container { max-width: 800px; margin: 0 auto; border: 3px solid #1e40af; padding: 30px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th { background-color: #f8fafc; padding: 12px; border: 1px solid #ddd; text-align: left; font-size: 15px; font-weight: bold; color: #1e40af; }
        td { padding: 10px 12px; border: 1px solid #ddd; font-size: 15px; color: #333; }
        tr.total { font-weight: bold; background-color: #f1f5f9; color: #1e40af; }
      </style>
    </head>
    <body>
      <div class="invoice-container">
        <!-- HEADER -->
        <div style="text-align: center; margin-bottom: 25px; border-bottom: 2px solid #1e40af; padding-bottom: 20px;">
           ${logoDataUri ? `<img src="${logoDataUri}" style="max-width: 100px; margin-bottom: 15px;">` : ''}
           <h1 style="margin: 0; font-size: 20px; color: #1e40af; text-transform: uppercase;">${isReEdited ? "RE-EDIT " : ""}Tax Invoice - HSN Statement</h1>
           <p style="font-size: 14px; margin-top: 10px;">Invoice No: <strong>${sale.invoiceId}</strong> | Date: ${new Date(sale.createdAt || sale.orderDate || new Date()).toLocaleDateString("en-IN")}</p>
        </div>

        <table>
          <thead>
            <tr>
              <th>HSN Code</th>
              <th style="text-align: right;">Taxable Value</th>
              <th>CGST (Rate | Amt)</th>
              <th>SGST (Rate | Amt)</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            ${rowsHTML}
            <tr class="total">
              <td>TOTAL</td>
              <td style="text-align: right;">₹${totalTaxableValue.toFixed(2)}</td>
              <td>${totalIGST > 0 ? `IGST: ₹${totalIGST.toFixed(2)}` : `CGST: ₹${totalCGST.toFixed(2)}`}</td>
              <td>${totalIGST > 0 ? '' : `SGST: ₹${totalSGST.toFixed(2)}`}</td>
              <td style="text-align: right;">₹${sale.grandTotal.toFixed(2)}</td>
            </tr>
          </tbody>
        </table>

        ${backOrderHTML}

        <div class="certification" style="font-size: 11px; font-style: italic; color: #666; margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 15px;">
          Certified that the particulars given above are true and correct. Tax Invoice as per GST regulations.
        </div>
        <div class="copy-badge" style="text-align: right; font-weight: 800; color: #dc2626; font-size: 18px; margin-top: 15px; letter-spacing: 1px; text-transform: uppercase;">
          ${copyTitle}
        </div>
      </div>
    </body>
    </html>
    `;

  const browser = await launchBrowser();
  
  // If browser failed to launch, use placeholder
  if (!browser) {
    console.log("📄 Using placeholder for tax invoice (browser unavailable)");
    return await generatePlaceholderInvoice(sale, "tax");
  }
  
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 840, height: 1190, deviceScaleFactor: 2 });
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const imageBuffer = await page.screenshot({ type: 'png', fullPage: true, scale: 2 });
    await browser.close();

    const upload = await cloudinary.uploader.upload(
      `data:image/png;base64,${imageBuffer.toString('base64')}`,
      {
        folder: "pearls-erp/invoices",
        public_id: `INV_TAX_${sale.invoiceId}_${Date.now()}`,
      }
    );

    return upload.secure_url;
  } catch (err) {
    console.error("❌ Error generating tax page:", err);
    if (browser) await browser.close();
    // Fallback to placeholder if Puppeteer fails
    return await generatePlaceholderInvoice(sale, "tax");
  }
}

// PAGE 3: BACK ORDER
async function generateBackOrderPage(sale, backOrderSummary, invoiceNotes = "") {
  const logoDataUri = await getLogoDataUri();
  if (!backOrderSummary || backOrderSummary.length === 0) {
    return null;
  }

  const rowsHTML = backOrderSummary.map((item, idx) => `
    <tr>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 8px;">${idx + 1}</td>
      <td style="padding: 8px; border: 1px solid #ddd; font-size: 8px;">${item.product}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 8px;">${item.requestedQty} kg</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 8px;">${item.confirmedQty} kg</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 8px; color: #d32f2f; font-weight: bold;">${item.backOrderQty} kg</td>
    </tr>
  `).join('');

  const totalBackOrderQty = backOrderSummary.reduce((sum, item) => sum + item.backOrderQty, 0);
  const notesHTML = invoiceNotes ? `<div style="margin-top: 20px; padding: 10px; background-color: #f9f9f9; border: 1px solid #ddd; font-size: 11px;"><strong>Notes:</strong> ${invoiceNotes}</div>` : '';

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Back Order Summary</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; background: white; padding: 20px; }
        .invoice-container { max-width: 420px; margin: 0 auto; border: 3px solid #2b6cb0; padding: 15px; }
        .header { display: flex; gap: 10px; margin-bottom: 15px; justify-content: space-between; align-items: flex-start; }
        .company-info { flex: 1; }
        .company-info p { font-size: 11px; margin: 3px 0; color: #000; }
        h1 { text-align: center; color: #d32f2f; font-size: 16px; margin: 20px 0; }
        .details { display: flex; gap: 30px; margin: 15px 0; font-size: 11px; color: #000; }
        .detail-item { flex: 1; }
        .detail-item strong { display: block; margin-bottom: 2px; color: #000; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th { background-color: #f0f0f0; padding: 10px; border: 1px solid #ddd; text-align: left; font-size: 11px; font-weight: bold; color: #000; font-family: Arial, sans-serif; }
        td { padding: 10px 8px; border: 1px solid #ddd; font-size: 11px; color: #000; font-family: Arial, sans-serif; }
        .total-row { background-color: #f0f0f0; font-weight: bold; font-size: 11px; color: #000; }
      </style>
    </head>
    <body>
      <div class="invoice-container">
        <div class="header">
          ${logoDataUri ? `<img src="${logoDataUri}" style="max-width: 100px; max-height: 100px; object-fit: contain;">` : ''}
          <div class="company-info">
            <p><strong>${sale.branchId?.name || "PEARL AGENCY"}</strong></p>
            <p>${sale.branchId?.address || "12/13, South By-Pass Road, Vanarpettai"}</p>
            <p>${sale.branchId?.city || "Tirunelveli"} - ${sale.branchId?.pincode || "627003"}, ${sale.branchId?.state || "Tamil Nadu"}</p>
            <p>Mobile: ${sale.branchId?.phone || "9429692970"} | GSTIN: ${sale.branchId?.gstin || "33DULPS2600Q1Z6"}</p>
            <p>GPAY No: ${sale.branchId?.gpayNo || ""}</p>
          </div>
        </div>

        <h1>BACK ORDER SUMMARY</h1>

        <div class="details">
          <div class="detail-item">
            <strong>Invoice No: ${sale.invoiceId}</strong>
            <div>Date: ${new Date(sale.orderDate || sale.createdAt).toLocaleDateString("en-IN")}</div>
          </div>
          <div class="detail-item">
            <strong>Customer: ${sale.customer.name}</strong>
            <div>Phone: ${sale.customer.whatsapp}</div>
            <div>Address: ${sale.customer.address}</div>
            <div>${sale.customer.district}, ${sale.customer.state} - ${sale.customer.pincode}</div>
          </div>
        </div>

        <table>
          <tr style="background-color: #f0f0f0;">
            <th>Sr. No</th>
            <th>Product Name</th>
            <th>Requested Qty</th>
            <th>Confirmed Qty</th>
            <th>Back Order Qty</th>
          </tr>
          ${rowsHTML}
          <tr class="total-row">
            <td colspan="4" style="text-align: right;">Total Back Order Quantity:</td>
            <td style="text-align: center; color: #d32f2f;">${totalBackOrderQty} kg</td>
          </tr>
        </table>

        ${notesHTML}
      </div>
    </body>
    </html>
  `;

  const browser = await launchBrowser();
  
  // If browser failed to launch, use placeholder
  if (!browser) {
    console.log("📄 Using placeholder for back order invoice (browser unavailable)");
    return await generatePlaceholderInvoice(sale, "backorder");
  }
  
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 840, height: 1190, deviceScaleFactor: 2 });
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const imageBuffer = await page.screenshot({ type: 'png', fullPage: true, scale: 2 });
    await browser.close();

    const upload = await cloudinary.uploader.upload(
      `data:image/png;base64,${imageBuffer.toString('base64')}`,
      {
        folder: "pearls-erp/back-orders",
        public_id: `BACKORDER_${sale.invoiceId}_${Date.now()}`,
      }
    );

    return upload.secure_url;
  } catch (err) {
    console.error("❌ Error generating back order page:", err);
    if (browser) await browser.close();
    // Fallback to placeholder if Puppeteer fails
    return await generatePlaceholderInvoice(sale, "backorder");
  }
}

// E-WAY BILL
async function generateEwayBillImage(sale) {
  const logoDataUri = await getLogoDataUri();
  const itemsHTML = sale.items.map((item) => `
    <tr>
      <td style="padding: 8px; border: 1px solid #ddd; font-size: 8px;">${item.name}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 8px;">${item.qty}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: right; font-size: 8px;">₹${item.sellingPrice.toFixed(2)}</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 8px;">${item.gst}%</td>
      <td style="padding: 8px; border: 1px solid #ddd; text-align: right; font-size: 8px;">₹${((item.sellingPrice * item.gst) / 100).toFixed(2)}</td>
    </tr>
  `).join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>E-Way Bill</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Arial, sans-serif; background: white; padding: 20px; }
        .invoice-container { max-width: 420px; margin: 0 auto; border: 3px solid #2b6cb0; padding: 15px; }
        h1 { text-align: center; color: #805ad5; font-size: 14px; margin: 10px 0; font-weight: bold; }
        .sections { display: flex; gap: 15px; margin: 15px 0; flex-wrap: wrap; }
        .section { flex: 1; font-size: 11px; color: #000; }
        .section h3 { background-color: #f0f0f0; padding: 8px; font-size: 12px; margin-bottom: 8px; color: #000; }
        .section p { margin: 5px 0; color: #000; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th { background-color: #f0f0f0; padding: 8px; border: 1px solid #ddd; font-size: 11px; font-weight: bold; color: #000; }
        td { padding: 8px; border: 1px solid #ddd; font-size: 11px; color: #000; }
        .summary { margin-top: 20px; text-align: right; font-size: 11px; color: #000; }
        .summary-row { margin: 5px 0; padding: 5px 0; color: #000; }
      </style>
    </head>
    <body>
      <div class="invoice-container">
        ${logoDataUri ? `<div style="text-align: center; margin-bottom: 20px;"><img src="${logoDataUri}" style="max-width: 100px; max-height: 100px; object-fit: contain;"></div>` : ''}
        <h1>E-WAY BILL</h1>

        <div class="sections">
          <div class="section">
            <h3>Supplier (From)</h3>
            <p><strong>${sale.branchId?.name || "PEARL AGENCY"}</strong></p>
            <p>${sale.branchId?.address || "12/13, South By-Pass Road"}</p>
            <p>${sale.branchId?.city || "Tirunelveli"} - ${sale.branchId?.pincode || "627003"}</p>
            <p>Mobile No: ${sale.branchId?.phone || "9429692970"}</p>
            <p>GSTIN/UIN: ${sale.branchId?.gstin || "33DULPS2600Q1Z6"}</p>
            <p>GPAY No: ${sale.branchId?.gpayNo || ""}</p>
            <p>State: ${sale.branchId?.state || "Tamil Nadu"} (Code: ${sale.branchId?.stateCode || "33"})</p>
            <p>Warehouse: ${sale.warehouse}</p>
          </div>
          <div class="section">
            <h3>Recipient (To)</h3>
            <p><strong>Name: ${sale.customer.name}</strong></p>
            <p>Address: ${sale.customer.address}</p>
            <p>State: ${sale.customer.state} - ${sale.customer.pincode}</p>
          </div>
        </div>

        <table>
          <tr style="background-color: #f0f0f0;">
            <th>Product</th>
            <th>Qty</th>
            <th>Price</th>
            <th>GST%</th>
            <th>Tax Amount</th>
          </tr>
          ${itemsHTML}
        </table>

        <div class="summary">
          <div class="summary-row">Sub Total: <strong>₹${sale.subtotal.toFixed(2)}</strong></div>
          <div class="summary-row">Tax: <strong>₹${sale.totalTax.toFixed(2)}</strong></div>
          ${(sale.commonDiscount || sale.invoiceCommonDiscount) > 0 ? `<div class="summary-row">Discount: <strong style="color: #dc2626;">-₹${((sale.commonDiscount || sale.invoiceCommonDiscount) || 0).toFixed(2)}</strong></div>` : ''}
          <div class="summary-row">Transport: <strong>₹${(sale.transportCharge || 0).toFixed(2)}</strong></div>
          <div class="summary-row" style="border-top: 2px solid #ddd; padding-top: 8px; margin-top: 8px;">
            Grand Total: <strong style="font-size: 13px;">₹${sale.grandTotal.toFixed(2)}</strong>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

  const browser = await launchBrowser();
  
  // If browser failed to launch, use placeholder
  if (!browser) {
    console.log("📄 Using placeholder for e-way bill (browser unavailable)");
    return await generatePlaceholderInvoice(sale, "eway");
  }
  
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 840, height: 1190, deviceScaleFactor: 2 });
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const imageBuffer = await page.screenshot({ type: 'png', fullPage: true, scale: 2 });
    await browser.close();

    const upload = await cloudinary.uploader.upload(
      `data:image/png;base64,${imageBuffer.toString('base64')}`,
      {
        folder: "pearls-erp/e-way-bills",
        public_id: `EWAY_${sale.invoiceId}_${Date.now()}`,
      }
    );

    return upload.secure_url;
  } catch (err) {
    console.error("❌ Error generating e-way bill:", err);
    if (browser) await browser.close();
    // Fallback to placeholder if Puppeteer fails
    return await generatePlaceholderInvoice(sale, "eway");
  }
}

// Generate both Original and Copy 1 Tax Invoices ONLY (2 items total)
async function generateInvoiceImage(sale, backOrderSummary = [], invoiceNotes = "") {
  console.log("📄 Generating Dual Copy Tax Invoices (Original & Copy 1)...");
  
  const isReEdited = !!sale.isReEdited || !!sale.invoiceGenerated;
  const copies = isReEdited ? ["RE-EDIT ORIGINAL", "RE-EDIT COPY 1"] : ["ORIGINAL INVOICE", "COPY 1"];

  // ORIGINAL SET - Tax Invoice Only
  const originalTax = await generateInvoiceTaxPage(sale, copies[0], backOrderSummary, invoiceNotes, isReEdited);

  // COPY 1 SET - Tax Invoice Only
  const copy1Tax = await generateInvoiceTaxPage(sale, copies[1], backOrderSummary, invoiceNotes, isReEdited);

  return [
    originalTax,
    copy1Tax
  ];
}

router.post("/generate-invoice-preview/:id", async (req, res) => {
  try {
    const { editedItems = [], notes = "" } = req.body;

    const sale = await SalesOrder.findById(req.params.id)
      .populate('salesMan', 'name')
      .populate('deliveryMan', 'name')
      .populate('branchId')
      .lean();

    if (!sale) {
      return res.status(404).json({ message: "Sale not found" });
    }

    // Extract names from populated fields
    sale.salesManName = sale.salesMan?.name || "-";
    sale.deliveryManName = sale.deliveryMan?.name || "-";

    // Fetch customer details including GSTIN
    const customerDoc = await Customer.findById(sale.customer.customerId).select('gstin name').lean();
    if (customerDoc) {
      sale.customer.gstin = customerDoc.gstin || "-";
    }

    // Fetch billing person name (can be SalesOwner, SalesMan, or DeliveryMan)
    let billingPersonName = "-";
    if (sale.billingPerson) {
      // Try to find in SalesOwner first
      let billingPerson = await SalesOwner.findById(sale.billingPerson).select('name').lean();
      if (!billingPerson) {
        // Try SalesMan
        billingPerson = await SalesMan.findById(sale.billingPerson).select('name').lean();
      }
      if (!billingPerson) {
        // Try DeliveryMan
        billingPerson = await DeliveryMan.findById(sale.billingPerson).select('name').lean();
      }
      billingPersonName = billingPerson?.name || "-";
    }
    sale.billingPersonName = billingPersonName;

    // ✅ 1. CREATE ADJUSTED ITEMS FOR INVOICE using editedItems
    const invoicedItems = sale.items.map((item, idx) => {
      const editedItem = editedItems[idx];
      // Use confirmedQty from editedItems, fallback to original qty
      const adjustedQty = editedItem?.confirmedQty !== undefined ? editedItem.confirmedQty : item.qty;
      return {
        ...item,
        qty: adjustedQty,
        total: adjustedQty * item.sellingPrice - (item.discountAmount || 0),
      };
    });

    // Calculate back order summary
    const backOrderSummary = sale.items.map((item, idx) => {
      const editedItem = editedItems[idx];
      const requestedQty = item.qty;
      const confirmedQty = editedItem?.confirmedQty !== undefined ? editedItem.confirmedQty : item.qty;
      const backOrderQty = Math.max(0, requestedQty - confirmedQty);

      return {
        product: item.name,
        requestedQty,
        confirmedQty,
        backOrderQty,
      };
    }).filter(b => b.backOrderQty > 0);

    // Calculate updated totals for invoice
    let newSubtotal = 0;
    const taxBreakdown = { cgst: 0, sgst: 0, igst: 0, total: 0, hasIgst: false };
    
    invoicedItems.forEach(item => {
      const qty = item.qty;
      const baseAmount = item.sellingPrice * qty;
      newSubtotal += baseAmount;
      const taxable = baseAmount - (item.discountAmount || 0);
      
      const itemGst = (taxable * (item.gst || 0)) / 100;
      if (item.igst) {
        taxBreakdown.igst += itemGst;
        taxBreakdown.hasIgst = true;
      } else {
        taxBreakdown.cgst += itemGst / 2;
        taxBreakdown.sgst += itemGst / 2;
      }
    });

    // 💡 Add transport GST to the breakdown (using transportGstPercent from sale, default 18)
    const tCharge = sale.transportCharge || 0;
    const tGstPercent = sale.transportGstPercent || 18;
    const tGstAmount = (tCharge * tGstPercent) / 100;

    if (taxBreakdown.hasIgst) {
      taxBreakdown.igst += tGstAmount;
    } else {
      taxBreakdown.cgst += tGstAmount / 2;
      taxBreakdown.sgst += tGstAmount / 2;
    }
    taxBreakdown.total = taxBreakdown.igst + taxBreakdown.cgst + taxBreakdown.sgst;

    const newGrandTotal = newSubtotal + taxBreakdown.total + tCharge;

    // ✅ 2. CHECK STOCK (WAREHOUSE AWARE)
    await checkStockAvailability(invoicedItems, sale.warehouse);

    // ✅ 3. GENERATE INVOICE (with adjusted items)
    const invoiceData = {
      ...sale,
      items: invoicedItems,
      subtotal: newSubtotal,
      totalTax: taxBreakdown,
      grandTotal: newGrandTotal,
      invoiceNotes: notes,
      backOrderSummary: backOrderSummary,
    };

    const invoicePages = await generateInvoiceImage(invoiceData, backOrderSummary, notes);
    let ewayImage = null;

    if (sale.ewayEnabled) {
      ewayImage = await generateEwayBillImage(invoiceData);
    }

    // Generate back order page if there are back orders
    let backOrderImage = null;
    if (backOrderSummary && backOrderSummary.length > 0) {
      backOrderImage = await generateBackOrderPage(invoiceData, backOrderSummary, notes);
    }

    // ✅ Store adjustments for later confirmation
    const phone = `91${sale.customer.whatsapp}`;
    const customerLoginLink = "https://pearlsfrontend.web.app/customer-login";
    const message = encodeURIComponent(
      `Hello ${sale.customer.name},\n\nInvoice No: ${sale.invoiceId}\nAmount: ₹${newGrandTotal}\n\n📄 Invoice: ${invoicePages[0]}\n\n🛒 Pearls Shopping: ${customerLoginLink}`
    );

    // Prepare response with all pages
    const invoiceImages = [
      ...invoicePages,    // Original & Copy 1
      backOrderImage,     // Back Order page
    ].filter(Boolean);

    const invoiceLinks = invoiceImages.map((img, idx) => 
      img ? `${img}#page${idx + 1}` : null
    ).filter(Boolean);

    res.json({
      success: true,
      invoiceImages,          // Array of all 3 pages
      invoiceLinks,           // Shareable links
      invoiceImage: invoicePages[0],    // Order + Sample Items (backward compat)
      invoiceTaxPage: invoicePages[1],  // Tax Invoice
      ewayImage,
      backOrderImage,
      waUrl: `https://wa.me/${phone}?text=${message}`,
      editedItems,            // Send back edited items
      notes,                  // Send back notes
    });
  } catch (err) {
    console.error("INVOICE PREVIEW ERROR:", err);
    res.status(500).json({ message: err.message });
  }
});

// ✅ NEW ENDPOINT: Confirm invoice and perform all actions (reduce stock, update balance, create commissions)
router.post("/confirm-invoice/:id", async (req, res) => {
  try {
    const { stockAdjustments = {}, invoiceNotes = "", printConfirm = false, sendConfirm = false } = req.body;

    const sale = await SalesOrder.findById(req.params.id)
      .populate('salesMan', 'name')
      .populate('deliveryMan', 'name')
      .populate('branchId')
      .lean();

    if (!sale) {
      return res.status(404).json({ message: "Sale not found" });
    }

    // ✅ 1. CREATE ADJUSTED ITEMS FOR INVOICE
    const invoicedItems = sale.items.map((item, idx) => {
      const adjustedQty = stockAdjustments[idx] !== undefined ? stockAdjustments[idx] : item.qty;
      return {
        ...item,
        qty: adjustedQty,
        total: adjustedQty * item.sellingPrice - (item.discountAmount || 0),
      };
    });

    // Create adjusted sample items
    const invoicedSampleItems = sale.sampleItems.map((item, idx) => ({
      ...item,
      qty: item.qty, // Sample items typically don't change, but keep the option
    }));

    // Calculate back order summary
    const backOrderSummary = sale.items.map((item, idx) => {
      const requestedQty = item.qty;
      const confirmedQty = stockAdjustments[idx] !== undefined ? stockAdjustments[idx] : item.qty;
      const backOrderQty = Math.max(0, requestedQty - confirmedQty);

      return {
        product: item.name,
        requestedQty,
        confirmedQty,
        backOrderQty,
      };
    }).filter(b => b.backOrderQty > 0);

    // Calculate updated totals
    let newSubtotal = 0;
    let newTotalTax = 0;
    invoicedItems.forEach(item => {
      const qty = item.qty;
      const baseAmount = item.sellingPrice * qty;
      newSubtotal += baseAmount;
      const taxable = baseAmount - (item.discountAmount || 0);
      newTotalTax += (taxable * item.gst) / 100;
    });

    const newGrandTotal = newSubtotal + newTotalTax + (sale.transportCharge || 0);

    // ✅ 2. REDUCE STOCK (WAREHOUSE + FIFO) - using invoiced items
    const lowStockAlerts = await reduceStockFIFO(invoicedItems, sale.warehouse);

    // ✅ 3. REDUCE STOCK FOR SAMPLE ITEMS
    if (sale.sampleItems && Array.isArray(sale.sampleItems) && sale.sampleItems.length > 0) {
      console.log(`\n📦 Processing ${sale.sampleItems.length} sample items for stock reduction...`);
      await reduceStockFIFO(sale.sampleItems, sale.warehouse);
    }

    // ✅ 4. UPDATE CUSTOMER BALANCE
    const invoiceAmount = newGrandTotal;
    const customer = await Customer.findById(sale.customer.customerId);

    if (!customer) {
      throw new Error("Customer not found");
    }

    // Invoice opening balance is the current customer closing balance
    const invoiceOpeningBalance = customer.closingBalance;
    const invoiceClosingBalance = invoiceOpeningBalance + invoiceAmount;

    // Update customer's actual closing balance
    await Customer.findByIdAndUpdate(sale.customer.customerId, {
      closingBalance: invoiceClosingBalance,
      totalBalance: invoiceClosingBalance,
    });

    // ✅ 5. UPDATE ORIGINAL SALES ORDER WITH INVOICE DETAILS (KEEP ORIGINAL ITEMS)
    // Save adjusted items in invoiceItems field, keep original items unchanged
    const updatedSale = await SalesOrder.findByIdAndUpdate(req.params.id, {
      invoiceItems: invoicedItems,
      invoiceSampleItems: invoicedSampleItems,
      invoiceSubtotal: newSubtotal,
      invoiceTotalTax: newTotalTax,
      invoiceGrandTotal: newGrandTotal,
      invoiceTransportCharge: sale.transportCharge || 0,
      invoiceOpeningBalance: invoiceOpeningBalance,
      invoiceClosingBalance: invoiceClosingBalance,
      invoiceNotes: invoiceNotes,
      backOrderSummary: backOrderSummary,
      invoiceGenerated: true,
    }, { new: true });

    console.log(`✅ SALES INVOICE updated: ${updatedSale._id}`);

    console.log(`✅ Customer balance updated: ₹${invoiceOpeningBalance} → ₹${invoiceClosingBalance}`);

    // ✅ 6. CREATE COMMISSIONS
    try {
      const salesOwnerDoc = sale.salesOwner ? await SalesOwner.findById(sale.salesOwner) : null;
      const salesManDoc = sale.salesMan ? await SalesMan.findById(sale.salesMan) : null;
      const deliveryManDoc = sale.deliveryMan ? await DeliveryMan.findById(sale.deliveryMan) : null;

      const getCommission = async (personId, roleType) => {
        if (!personId) return { percentage: 0, amount: 0 };

        const rule = await CommissionRule.findOne({
          personId: personId,
          roleType: roleType,
          minimumOrderValue: { $lte: invoiceAmount },
          isActive: true,
        }).sort({ minimumOrderValue: -1 });

        if (!rule) return { percentage: 0, amount: 0 };

        const commissionAmount = (invoiceAmount * rule.commissionPercentage) / 100;
        return { percentage: rule.commissionPercentage, amount: commissionAmount };
      };

      const soCommission = await getCommission(sale.salesOwner, "SalesOwner");
      const smCommission = await getCommission(sale.salesMan, "SalesMan");
      const dmCommission = await getCommission(sale.deliveryMan, "DeliveryMan");

      const commissionData = {
        salesOrderId: req.params.id,
        orderValue: invoiceAmount,
        invoiceId: sale.invoiceId,
        salesOwnerId: salesOwnerDoc?._id,
        salesOwnerName: salesOwnerDoc?.name,
        salesOwnerCommissionPercentage: soCommission.percentage,
        salesOwnerCommissionAmount: soCommission.amount,
        salesManId: salesManDoc?._id,
        salesManName: salesManDoc?.name,
        salesManCommissionPercentage: smCommission.percentage,
        salesManCommissionAmount: smCommission.amount,
        deliveryManId: deliveryManDoc?._id,
        deliveryManName: deliveryManDoc?.name,
        deliveryManCommissionPercentage: dmCommission.percentage,
        deliveryManCommissionAmount: dmCommission.amount,
      };

      commissionData.totalCommission =
        commissionData.salesOwnerCommissionAmount +
        commissionData.salesManCommissionAmount +
        commissionData.deliveryManCommissionAmount;

      const commission = new Commission(commissionData);
      await commission.save();

      if (commission.salesOwnerId && commission.salesOwnerCommissionAmount > 0) {
        await SalesOwner.findByIdAndUpdate(commission.salesOwnerId, {
          $inc: { commissionAmount: commission.salesOwnerCommissionAmount }
        });
        console.log(`✅ Sales Owner commission added: ₹${commission.salesOwnerCommissionAmount}`);
      }

      if (commission.salesManId && commission.salesManCommissionAmount > 0) {
        await SalesMan.findByIdAndUpdate(commission.salesManId, {
          $inc: { commissionAmount: commission.salesManCommissionAmount }
        });
        console.log(`✅ Sales Man commission added: ₹${commission.salesManCommissionAmount}`);
      }

      if (commission.deliveryManId && commission.deliveryManCommissionAmount > 0) {
        await DeliveryMan.findByIdAndUpdate(commission.deliveryManId, {
          $inc: { commissionAmount: commission.deliveryManCommissionAmount }
        });
        console.log(`✅ Delivery Man commission added: ₹${commission.deliveryManCommissionAmount}`);
      }

      console.log("✅ Commission record created:", commission._id);
    } catch (commissionError) {
      console.error("⚠️ Commission creation failed:", commissionError.message);
    }

    // ✅ 7. GENERATE INVOICE AND BACK ORDER IMAGES
    const invoiceData = {
      ...sale,
      items: invoicedItems,
      sampleItems: invoicedSampleItems,
      subtotal: newSubtotal,
      totalTax: newTotalTax,
      grandTotal: newGrandTotal,
      transportCharge: sale.transportCharge || 0,
      invoiceNotes: invoiceNotes,
      backOrderSummary: backOrderSummary,
      openingBalance: invoiceOpeningBalance,
      closingBalance: invoiceClosingBalance,
    };

    // ✅ 7. GENERATE DUAL-COPY INVOICE (Tax Invoice now includes Back Order)
    const invoicePages = await generateInvoiceImage(invoiceData, backOrderSummary, invoiceNotes);

    const invoiceImages = [
      ...invoicePages
    ].filter(Boolean);

    // ✅ 8. HANDLE PRINT & SEND ACTIONS BASED ON CHECKBOXES
    let printAction = null;
    let whatsappAction = null;

    // Handle Print & Confirm
    if (printConfirm) {
      printAction = {
        enabled: true,
        invoiceImages: invoiceImages,
        ewayImage: invoiceData.ewayEnabled ? invoicePages[1] : null, // Eway corresponds to Tax Invoice logic usually
        instructions: "Ready to print dual invoice copies. Please proceed.",
      };
    }

    // Handle Send & Confirm (WhatsApp)
    if (sendConfirm) {
      const phone = `91${sale.customer.whatsapp}`;
      const customerLoginLink = "https://pearlsfrontend.web.app/customer-login";
      const message = encodeURIComponent(
        `Hello ${sale.customer.name},\n\nInvoice No: ${sale.invoiceId}\nAmount: ₹${newGrandTotal}\n\n📄 Invoice has been generated\n\n🛒 View at: ${customerLoginLink}`
      );

      whatsappAction = {
        enabled: true,
        waUrl: `https://wa.me/${phone}?text=${message}`,
        phone: phone,
        customerName: sale.customer.name,
        invoiceId: sale.invoiceId,
        amount: newGrandTotal,
        instructions: "Ready to send invoice via WhatsApp. Please confirm to open WhatsApp.",
      };
    }

    const responseData = {
      success: true,
      message: "Invoice confirmed and all actions completed",
      lowStockAlerts,
      invoiceImages
    };

    // Add actions based on checkbox selection
    if (printAction && whatsappAction) {
      responseData.actions = {
        printAction,
        whatsappAction,
        executionOrder: "print_then_send"
      };
    } else if (printAction) {
      responseData.actions = {
        printAction
      };
    } else if (whatsappAction) {
      responseData.actions = {
        whatsappAction
      };
    }

    res.json(responseData);
  } catch (err) {
    console.error("INVOICE CONFIRM ERROR:", err);
    res.status(500).json({ message: err.message });
  }
});

// Keep old endpoint for backward compatibility (now just calls preview)
router.post("/generate-invoice/:id", async (req, res) => {
  try {
    const { editedItems = [], notes = "" } = req.body;

    const sale = await SalesOrder.findById(req.params.id)
      .populate('salesMan', 'name')
      .populate('deliveryMan', 'name')
      .lean();

    if (!sale) {
      return res.status(404).json({ message: "Sale not found" });
    }

    // Extract names from populated fields
    sale.salesManName = sale.salesMan?.name || "-";
    sale.deliveryManName = sale.deliveryMan?.name || "-";

    // Fetch customer details including GSTIN
    const customerDoc = await Customer.findById(sale.customer.customerId).select('gstin name').lean();
    if (customerDoc) {
      sale.customer.gstin = customerDoc.gstin || "-";
    }

    // Fetch billing person name
    let billingPersonName = "-";
    if (sale.billingPerson) {
      let billingPerson = await SalesOwner.findById(sale.billingPerson).select('name').lean();
      if (!billingPerson) {
        billingPerson = await SalesMan.findById(sale.billingPerson).select('name').lean();
      }
      if (!billingPerson) {
        billingPerson = await DeliveryMan.findById(sale.billingPerson).select('name').lean();
      }
      billingPersonName = billingPerson?.name || "-";
    }
    sale.billingPersonName = billingPersonName;

    // ✅ 1. CREATE ADJUSTED ITEMS FOR INVOICE using editedItems
    const invoicedItems = sale.items.map((item, idx) => {
      const editedItem = editedItems[idx];
      const adjustedQty = editedItem?.confirmedQty !== undefined ? editedItem.confirmedQty : item.qty;
      return {
        ...item,
        qty: adjustedQty,
        total: adjustedQty * item.sellingPrice - (item.discountAmount || 0),
      };
    });

    // Calculate back order summary
    const backOrderSummary = sale.items.map((item, idx) => {
      const editedItem = editedItems[idx];
      const requestedQty = item.qty;
      const confirmedQty = editedItem?.confirmedQty !== undefined ? editedItem.confirmedQty : item.qty;
      const backOrderQty = Math.max(0, requestedQty - confirmedQty);

      return {
        product: item.name,
        requestedQty,
        confirmedQty,
        backOrderQty,
      };
    }).filter(b => b.backOrderQty > 0);

    // Calculate updated totals for invoice
    let newSubtotal = 0;
    let newTotalTax = 0;
    invoicedItems.forEach(item => {
      const qty = item.qty;
      const baseAmount = item.sellingPrice * qty;
      newSubtotal += baseAmount;
      const taxable = baseAmount - (item.discountAmount || 0);
      newTotalTax += (taxable * item.gst) / 100;
    });

    const newGrandTotal = newSubtotal + newTotalTax + (sale.transportCharge || 0);

    // ✅ 2. CHECK STOCK
    await checkStockAvailability(invoicedItems, sale.warehouse);

    // ✅ 3. GENERATE INVOICE
    const invoiceData = {
      ...sale,
      items: invoicedItems,
      subtotal: newSubtotal,
      totalTax: newTotalTax,
      grandTotal: newGrandTotal,
      invoiceNotes: notes,
      backOrderSummary: backOrderSummary,
    };

    const invoicePages = await generateInvoiceImage(invoiceData, backOrderSummary, notes); // Now returns array of 4, Tax pages include Back Order

    if (sale.ewayEnabled) {
      ewayImage = await generateEwayBillImage(invoiceData);
    }

    // ✅ 4. REDUCE INVENTORY for invoiced items (only what was actually confirmed/invoiced)
    console.log("📦 Reducing inventory for invoiced items...");
    for (const item of invoicedItems) {
      await Product.findByIdAndUpdate(
        item.productId,
        {
          $inc: { totalQty: -item.qty } // Reduce inventory by INVOICED quantity (not original order qty)
        },
        { new: true }
      );
      console.log(`✅ Inventory reduced for ${item.name}: -${item.qty} units`);
    }

    // ✅ 5. MARK SALES ORDER AS INVOICED
    await SalesOrder.findByIdAndUpdate(
      req.params.id,
      {
        invoiceGenerated: true,
        invoiceItems: invoicedItems,
        invoiceSubtotal: newSubtotal,
        invoiceTotalDiscount: invoicedItems.reduce((sum, item) => sum + (item.discountAmount || 0), 0),
        invoiceTotalTax: newTotalTax,
        invoiceTransportCharge: sale.transportCharge || 0,
        invoiceGrandTotal: newGrandTotal,
        backOrderSummary: backOrderSummary,
      },
      { new: true }
    );
    console.log("✅ SalesOrder marked as invoiceGenerated");

    // ✅ WHATSAPP
    const phone = `91${sale.customer.whatsapp}`;
    const customerLoginLink = "https://pearlsfrontend.web.app/customer-login";
    const message = encodeURIComponent(
      `Hello ${sale.customer.name},\n\nInvoice No: ${sale.invoiceId}\nAmount: ₹${newGrandTotal}\n\n📄 Invoice: ${invoicePages[0]}\n\n🛒 Pearls Shopping: ${customerLoginLink}`
    );

    // Prepare response with all pages
    const invoiceImages = [
      ...invoicePages,    // Original & Copy 1
    ].filter(Boolean);

    const invoiceLinks = invoiceImages.map((img, idx) => 
      img ? `${img}#page${idx + 1}` : null
    ).filter(Boolean);

    res.json({
      success: true,
      invoiceImages,          // Array of all 4 pages
      invoiceLinks,           // Shareable links
      invoiceImage: invoicePages[0],    // Order + Sample Items (backward compat)
      invoiceTaxPage: invoicePages[1],  // Tax Invoice + Back Order
      ewayImage,
    });
  } catch (err) {
    console.error("INVOICE ERROR:", err);
    res.status(500).json({ message: err.message });
  }
});

export default router;
